### ISSUE TITLE
How to use temporary library in itest

### ISSUE THREAD

**Issue by sake92** [lefou/mill-integrationtest#198]
Is it possible to use `temporaryIvyModules` to publish a library, and then depend on it in an `itest` project?
Seems like it does publish the artifact, but not sure how to depend on it, what should I put as version?

Tried ivy"ba.sake::squery:${VcsVersion.vcsState().format()}" but it doesnt resolve it.  
This is the project btw https://github.com/sake92/squery

**Comment by lefou** [comment]
Since you want to access some information only present in the outer build, the easiest way would be to generate it. You could either use the `BuildInfo` plugin provided by Mill, or just generate a script file which you could use in your `build.sc` under test.

There is already support via the `perTestReosurces` target, which could look like this:

```scala
   override def perTestResources = T.sources { 
     os.write( 
       T.dest / "versions.sc", 
       s"""object Versions {
         val squeryVersion = "${squery.publishVersion()}"
       }
     )
     Seq(PathRef(T.dest))
   } 
```

And in your `build.sc` under test, you could the write:

```scala
import $file.versions
...
  def ivyDeps = Seq(ivy"...${verisons.Versions.squery}")
...
```

mill-integrationtest itself is using this. Have a look at 
https://github.com/lefou/mill-integrationtest/blob/93bc4fe1ec0c85a750a94a7d690303bfa9540f0a/build.sc#L154-L162

**Comment by sake92** [comment]
Thank you very much, it works as a charm!  https://github.com/sake92/squery/commit/62901e84afbbbac402c395b3f207e7a45cfda9b7

**Comment by lefou** [comment]
Great!
